name: BoxPvPCore
version: 1.0.0
main: com.boxpvp.core.BoxPvPCore
api-version: '1.16'
author: YourName
description: Core plugin for Box PvP gamemode

commands:
  spawn:
    description: Teleport to spawn point
    usage: /<command>
    aliases: [hub]
  
  stats:
    description: View your player statistics
    usage: /<command> [player]
    aliases: [statistics]
  
  arena:
    description: Join or manage arena matches
    usage: /<command> [join|leave|list]
    aliases: [pvp, duel]
  
  setspawn:
    description: Set the spawn point (Admin only)
    usage: /<command>
    permission: boxpvp.admin
  
  warp:
    description: Teleport to a warp location (trade, crate, afk)
    usage: /<command> [name]
    aliases: [warps]
  
  setwarp:
    description: Set a warp location (Admin only)
    usage: /<command> <name>
    permission: boxpvp.admin
  
  trade:
    description: Trade items with nearby players
    usage: /<command> <player>
    aliases: [t]
  
  ah:
    description: Access the auction house (black market)
    usage: /<command> [sell <price> <money|gems|coins>]
    aliases: [auctionhouse, blackmarket, market]

permissions:
  boxpvp.admin:
    description: Access to admin commands
    default: op
  boxpvp.player:
    description: Access to basic player commands
    default: true
